### ISSUE TITLE
Update generated pages for working getting started guide

### ISSUE THREAD

**Issue by jaidetree** [hashobject/perun.io#26]
# REPRODUCTION

1. Visit https://perun.io/guides/getting-started/#step-2-create-a-new-directory-add-a-file
2. Create a build.boot file:
    ```
    (set-env!
     :source-paths #{"content"}
     :dependencies '[[perun "0.4.2-SNAPSHOT" :scope "test"]])

    (require '[io.perun :as perun])
    ``

3.  Create a `boot.properties` file:
    ```
    #http://boot-clj.com
    #Mon Jan 18 23:19:36 CET 2016
    BOOT_CLOJURE_NAME=org.clojure/clojure
    BOOT_CLOJURE_VERSION=1.8.0
    BOOT_VERSION=2.7.2
    BOOT_EMIT_TARGET=no
    ```

4. Create content/index.markdown:
   ```
   # Hello World
   We are making a website!
   ```

5. Run `boot markdown` in terminal.

## EXPECTED

- I should see `[markdown] - rendered new or changed file public/index.html`
- Markdown is generated (albeit no files written)

## ACTUAL

Error is thrown:

![screen shot 2019-01-12 at 1 56 02 pm](https://user-images.githubusercontent.com/590297/51077258-ddcfa800-1671-11e9-9536-b0fa2702d9fc.png)


```
Boot.main                          Boot.java:  257
      ...
jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke  DelegatingMethodAccessorImpl.java:   43
jdk.internal.reflect.NativeMethodAccessorImpl.invoke      NativeMethodAccessorImpl.java:   62
jdk.internal.reflect.NativeMethodAccessorImpl.invoke0       NativeMethodAccessorImpl.java
boot.App.main                           App.java:  500
boot.App.runBoot                           App.java:  407
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke        ClojureRuntimeShimImpl.java:  150
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke        ClojureRuntimeShimImpl.java:  159
      ...
boot.main/-main                           main.clj:  216
boot.main/-main/fn                           main.clj:  216
clojure.core/load-string                           core.clj: 4089
clojure.core/load-reader                           core.clj: 4087
      ...
boot.user$eval165.invoke                                   :    8
boot.user$eval165.invokeStatic                                   :    8
      ...
clojure.core/use                           core.clj: 6093 (repeats 2 times)
clojure.core/apply                           core.clj:  669
      ...
clojure.core/load-libs                           core.clj: 5969
clojure.core/load-libs                           core.clj: 5985
clojure.core/apply                           core.clj:  667
      ...
clojure.core/load-lib                           core.clj: 5928
clojure.core/load-lib                           core.clj: 5966
clojure.core/apply                           core.clj:  667
      ...
clojure.core/refer                           core.clj: 4217
clojure.core/refer                           core.clj: 4252
      ...
java.lang.IllegalStateException: trace already refers to: #'boot.util/trace in namespace: boot.user
clojure.lang.ExceptionInfo: trace already refers to: #'boot.util/trace in namespace: boot.user
line: 8
```

**Comment by jaidetree** [comment]
Discovered it has been updated https://github.com/hashobject/perun.io/blob/master/resources/guides/getting-started.md. Does it just need to be published?

**Comment by allentiak** [comment]
Hi, @podviaznikov. Could you please update the published HTML file?

**Comment by allentiak** [comment]
@eccentric-j I guess renaming the title to something like "Update generated pages" may help closing this.

**Comment by podviaznikov** [comment]
Yes, I will try to publish new version soonish.

**Comment by allentiak** [comment]
Hi, @podviaznikov ,

Could you please let me know whether I could help you close this one, please? All is needed is access to the AWS infra...

Best,
Leandro

**Comment by podviaznikov** [comment]
Published new version myself!
