### ISSUE TITLE
Multiple problems with Java 11

### ISSUE THREAD

**Issue by allentiak** [hashobject/perun.io#28]
Hi,

I'm just following perun's "Getting Started" guide, with Clojure 1.10 and Java 11. I'm getting errors executing multiple tasks.

- markdown (probably upstream, related to the YAML library used for parsing - the task "markdown*" works fine)
-  print-meta

Has perun been tested with Java 11? Or are these upstream (Boot) bugs?

[Logfile](https://github.com/hashobject/perun.io/files/2848060/perun.output.txt)

**Comment by allentiak** [comment]
After reading the Built-Ins Guide, it seems that the Java-related YAML problems belong to (order versions of) the upstream YAML parser, flexmark-java (see https://github.com/vsch/flexmark-java/issues/283).

However, I could not find any mention to the library in the `build.boot` file...

**Comment by jaidetree** [comment]
This project is my introduction to boot so I may be wrong but one of the freedoms of the tool is getting to use Clojure to build the tooling around the project. The tradeoff is that there many not be a single place to look for resources.

In perun the deps for each task are usually placed above the task definition in the main task file:

https://github.com/hashobject/perun/blob/master/src/io/perun.clj#L401

Then those dep vars are scooped up and added to the boot deps dynamically:

https://github.com/hashobject/perun/blob/master/build.boot#L9

**Comment by allentiak** [comment]
Thanks a lot for the pointer, Jay!

I can see that, as of today, flexmark's latest version is 0.40.16 (released on
2019.01.29). The one currently used by Perun is... 0.15.1 (released on
2017.02.18).

Therefore, the dependency versions are quite old...

**Comment by jaidetree** [comment]
Created a PR to support Java 11. Since it's unknown when a new release will happen I have deployed fixes to support Java 11 and Clojure 1.9+ at https://clojars.org/idle-parens/perun. You can replace the perun dependency with that fork to get those fixes.

**Comment by allentiak** [comment]
@bhagany @podviaznikov
Would it be OK merging this?

@eccentric-j Thanks for the fix!
On the other hand, I'm not so sure whether it is convenient to publish a fork you don't seem to intend to maintain... If people start using it, you will have the pressure to keep it up to date...
(Just a thought, though.)

**Comment by allentiak** [comment]
https://github.com/hashobject/perun/pull/223 has been merged.
